version: '3.3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8070:80
    depends_on:
      - app
    volumes:
      - static:/label-studio/label_studio:rw
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/conf.d/default.conf:ro
    command: nginx -g "daemon off;"

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    expose:
      - "8070"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST_ENV:-""}
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME_ENV}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD_ENV}
      - GOOGLE_APPLICATION_CREDENTIALS=./dingbro-ai-storage.json
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
    volumes:
      - ./mydata:/label-studio/data:rw
      - static:/label-studio/label_studio:rw
    command: [ "./deploy/wait-for-postgres.sh", "db", "bash", "/label-studio/deploy/start_label_studio.sh" ]

  db:
    image: postgres:11.5
    hostname: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data


volumes:
  static: {} 

# If docker-compose down not work, check https://movefast.tistory.com/189